# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install necessary packages
RUN pip install --no-cache-dir requests psycopg2-binary confluent-kafka

# Run the consumer script when the container launches
CMD ["python3", "./workload.py"]
